### PR TITLE
Fix geometry selection

### PR DESCRIPTION
**Pull request by MustafaMustafa**
The choice of geometry should be mutually exclusive.

### CODE REVIEW

**Comment by MustafaMustafa** [comment]
Hi @plexoos 

I think these changes are straightforward. How do I push them to CVS?

**Comment by plexoos** [comment]
So, you are saying a geometry cannot be ideal and come from the DB at the same time :)  Isn't it enough to have a single flag to control application of optional misalignments/corrections coming from the DB?

**Comment by MustafaMustafa** [comment]
Geometry in the DB can be ideal, the choice is between using whatever is loaded in the DB and using the ideal directly from the CAVES. It is not enough to use the DB one all the time, at least in dev, we have situations where we want to load something in the DB and using something ideal geometry in the simulator.

I agree that it is enough to have single flag, I think it is a bad decision that I made years ago. I will fix that.

**Comment by MustafaMustafa** [comment]
Thank you for the comment @plexoos, fixed in this version.

**Comment by zaglamir** [comment]
@MustafaMustafa Unless I misunderstand, in line 106 & 107 shouldn't at least one of them be negated, such that if the user calls useIdeal, useDb is set to FALSE?

**Comment by MustafaMustafa** [comment]
@zaglamir, that is correct. That is why they have different defaults in the methods declarations. Isn't that what you meant?

**Comment by zaglamir** [comment]
@MustafaMustafa I understand that the defaults are different, but right now the result for a user of:
pxlFast->useIdealGeom(true);
OR
pxlFast->userDbGeom(true);

both result in using the DB geometry. Since those are both public functions, I expect that a user might at some point want to make those calls, and the current method naming convention makes it seem like it should be:
void StPxlSimMaker::useIdealGeom(bool db) { mUseDbGeom = !db;}

such that the ideal geometry is retrieved when "useIdealGeom(true)" is called.

**Comment by MustafaMustafa** [comment]
@zaglamir, 
You are correct. Thanks for the catch. Fixed. 

In principle we shouldn't have methods for this, but don't want to create problems in codes that are already using these.

**Comment by plexoos** [comment]
Looks good to me. I think you can merge with master. You may want to squash the commits in a single one before adding it in CVS. The cvs branch in this repo will be updated automatically once you make the change in the official STAR CVS. You can use the following command to add changes in STAR CVS:

    git cvsexportcommit -w ~/star_cvs/StRoot -u -p -c <commit_SHA>

where ~/star_cvs/StRoot should be your local checkout of corresponding codes from CVS

**Comment by MustafaMustafa** [comment]
Thank you @plexoos and @zaglamir 
I squashed the commits into one and added 520586158fca65a4c8e7bceaba733802752057a0  to CVS. 
I am not sure if I should add the merge commit too (b3c1dca779d4190e9cdaa3c07e9955de113d9025).

**Pull request merged**
